### ISSUE TITLE
iwm(4) fails to change power state from D3 to D0 when if_iwm.ko is loaded

### ISSUE THREAD

**Issue by evilgjb** [rpaulo/iwm#4]
As it turns out, and my endless "Thank you" to Adrian for requesting the relevant files which made me realize my configuration mistake, the iwm(4) issues where the device does not attach were due to a mistake on my part.

To reproduce the issue:

Add to loader.conf:
`
 hw.pci.do_power_nodriver=3
`

Add to sysctl.conf:
`
 hw.pci.do_power_nodriver=0
`

After rebooting the system, loading if_iwm.ko should show:

`root@nucleus:~ # pciconf -lvec iwm0@pci0:4:0:0`
`iwm0@pci0:4:0:0:        class=0x028000 card=0xc2708086 chip=0x08b28086 rev=0x83 hdr=0x00`
`  vendor     = 'Intel Corporation'`
`  class      = network`
`  cap 01[c8] = powerspec 3  supports D0 D3  current D3`
`  cap 05[d0] = MSI supports 1 message, 64 bit`
`  cap 10[40] = PCI-Express 2 endpoint max data 128(128) FLR link x1(x1)`
`   speed 2.5(2.5) ASPM L1(L0s/L1)`
`  ecap 0001[100] = AER 1 0 fatal 0 non-fatal 1 corrected`
`  ecap 0003[140] = Serial 1 5c514ffffff56f31`
`  ecap 0018[14c] = LTR 1`
`  ecap 000b[154] = Vendor 1 ID 51966`
`  PCI-e errors = Correctable Error Detected`
`                  Unsupported Request Detected`
`      Corrected = Advisory Non-Fatal Error`

Note the power state is `D3` not `D0`, regardless of the sysctl(8) rc script setting `hw.pci.do_nodriver_power=0`.

After removing the `hw.pci.do_nodriver_power` line from `loader.conf(5)`, the if_iwm.ko successfully attaches and is fully functional.

**Comment by rpaulo** [comment]
This looks like a bogus firmware. I use hw.pci.do_nodriver_power on my Lenovo X1 and it works just fine.

**Comment by rpaulo** [comment]
Please submit a FreeBSD bug if you disagree with my analysis.
