### ISSUE TITLE
Driver compile fails under Freebsd 10.1

### ISSUE THREAD

**Issue by telefax** [rpaulo/iwm#7]
I got the src installed in /usr/src and when I try to compile iwm according to the steps outlined in 
https://forums.freebsd.org/threads/how-can-i-solve-the-issue-with-driver-support.51980/#post-291606
the compilation fails, am I missing something? 
Thanks!
Firmware compiles fine btw.

# make
===> driver (all)
Warning: Object directory not changed from original /root/iwm/driver
@ -> /usr/src/sys
machine -> /usr/src/sys/amd64/include
x86 -> /usr/src/sys/x86/include
awk -f @/tools/makeobjops.awk @/kern/device_if.m -h
awk -f @/tools/makeobjops.awk @/kern/bus_if.m -h
awk -f @/tools/makeobjops.awk @/dev/pci/pci_if.m -h
:> opt_wlan.h
cc -O2 -pipe  -DIWM_DEBUG -fno-strict-aliasing -Werror -D_KERNEL -DKLD_MODULE -nostdinc  -I/root/iwm/driver -I. -I@ -I@/contrib/altq -fno-common -g -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer  -mno-aes -mno-avx -mcmodel=kernel -mno-red-zone -mno-mmx -mno-sse -msoft-float  -fno-asynchronous-unwind-tables -ffreestanding -fstack-protector -gdwarf-2 -std=iso9899:1999 -Qunused-arguments  -fstack-protector -Wall -Wredundant-decls -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Winline -Wcast-qual  -Wundef -Wno-pointer-sign -fformat-extensions  -Wmissing-include-dirs -fdiagnostics-show-option  -Wno-error-tautological-compare -Wno-error-empty-body  -Wno-error-parentheses-equality -Wno-error-unused-function   -c if_iwm.c
if_iwm.c:2351:17: error: use of undeclared identifier 'IEEE80211_R_IEEE'
        rxs.r_flags |= IEEE80211_R_IEEE | IEEE80211_R_FREQ;
                       ^
if_iwm.c:2351:36: error: use of undeclared identifier 'IEEE80211_R_FREQ'
        rxs.r_flags |= IEEE80211_R_IEEE | IEEE80211_R_FREQ;
                                          ^
if_iwm.c:2353:6: error: no member named 'c_ieee' in 'struct ieee80211_rx_stats'
        rxs.c_ieee = le16toh(phy_info->channel);
        ~~~ ^
if_iwm.c:2355:7: error: no member named 'c_freq' in 'struct ieee80211_rx_stats'
                rxs.c_freq = ieee80211_ieee2mhz(rxs.c_ieee, IEEE80211_CHAN_2GHZ);
                ~~~ ^
if_iwm.c:2355:39: error: no member named 'c_ieee' in 'struct ieee80211_rx_stats'
                rxs.c_freq = ieee80211_ieee2mhz(rxs.c_ieee, IEEE80211_CHAN_2GHZ);
                                                ~~~ ^
if_iwm.c:2357:7: error: no member named 'c_freq' in 'struct ieee80211_rx_stats'
                rxs.c_freq = ieee80211_ieee2mhz(rxs.c_ieee, IEEE80211_CHAN_5GHZ);
                ~~~ ^
if_iwm.c:2357:39: error: no member named 'c_ieee' in 'struct ieee80211_rx_stats'
                rxs.c_freq = ieee80211_ieee2mhz(rxs.c_ieee, IEEE80211_CHAN_5GHZ);
                                                ~~~ ^
if_iwm.c:2368:35: error: no member named 'c_freq' in 'struct ieee80211_rx_stats'
                tap->wr_chan_freq = htole16(rxs.c_freq);
                                            ~~~ ^
@/sys/endian.h:71:32: note: expanded from macro 'htole16'
#define htole16(x)      ((uint16_t)(x))
if_iwm.c:2420:3: error: implicit declaration of function 'if_inc_counter' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
                if_inc_counter(ifp, IFCOUNTER_OERRORS, 1);
                ^
if_iwm.c:2420:23: error: use of undeclared identifier 'IFCOUNTER_OERRORS'
                if_inc_counter(ifp, IFCOUNTER_OERRORS, 1);
                                    ^
if_iwm.c:2424:23: error: use of undeclared identifier 'IFCOUNTER_OPACKETS'
                if_inc_counter(ifp, IFCOUNTER_OPACKETS, 1);
                                    ^
if_iwm.c:2901:23: error: use of undeclared identifier 'IFCOUNTER_OERRORS'
                if_inc_counter(ifp, IFCOUNTER_OERRORS, 1);
                                    ^
if_iwm.c:3837:24: error: use of undeclared identifier 'IFCOUNTER_OERRORS'
                        if_inc_counter(ifp, IFCOUNTER_OERRORS, 1);
                                            ^
if_iwm.c:3890:24: error: use of undeclared identifier 'IFCOUNTER_OERRORS'
                        if_inc_counter(ifp, IFCOUNTER_OERRORS, 1);
                                            ^
if_iwm.c:4772:6: error: no member named 'ic_softc' in 'struct ieee80211com'
        ic->ic_softc = sc;
        ~~  ^
if_iwm.c:4773:6: error: no member named 'ic_name' in 'struct ieee80211com'; did you mean 'ic_wme'?
        ic->ic_name = device_get_nameunit(sc->sc_dev);
            ^~~~~~~
            ic_wme
@/net80211/ieee80211_var.h:205:29: note: 'ic_wme' declared here
        struct ieee80211_wme_state ic_wme;      /* WME/WMM state */
                                   ^
if_iwm.c:4773:14: error: assigning to 'struct ieee80211_wme_state' from incompatible type 'const char *'
        ic->ic_name = device_get_nameunit(sc->sc_dev);
                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
if_iwm.c:4877:22: error: incompatible pointer types assigning to 'void (*)(struct ifnet *)' from
      'void (struct ieee80211com *)' [-Werror,-Wincompatible-pointer-types]
        ic->ic_update_mcast = iwm_update_mcast;
                            ^ ~~~~~~~~~~~~~~~~
18 errors generated.
*** Error code 1

Stop.
make[1]: stopped in /root/iwm/driver
*** Error code 1

Stop.
make: stopped in /root/iwm

**Comment by rpaulo** [comment]
Yeah, it's not expected to work on FreeBSD 10 without a bit of effort. I don't have time to do it, but patches are welcome.
